### ISSUE TITLE
Saknar teamet!!!

### ISSUE THREAD

**Issue by salgo60** [VisbyStar/Swedish-Museum#1]
![The winner takes it all](https://3.bp.blogspot.com/-twonMVdPEnM/WAfMTuECD8I/AAAAAAAAiwo/x85S4tKN7Z0CgUB-JdiudtZyYIVMqylAACLcB/s1600/30350870926_6853d3ca3c_k.jpg)

Se https://visbystar.github.io/Swedish-Museum/

**Comment by VisbyStar** [comment]
Join us at GitHub!
